FROM ubuntu:22.04

RUN apt update && apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev \
libxft-dev libxext-dev python3 libssl-dev gfortran libpcre3-dev \
xlibmesa-glu-dev libftgl-dev \
libmariadb-dev libfftw3-dev libcfitsio-dev \
graphviz-dev libavahi-compat-libdnssd-dev \
libldap2-dev libxml2-dev libkrb5-dev \
libgsl0-dev qtwebengine5-dev build-essential git python2-dev python3-dev


