#FROM rootproject/root:6.26.02-ubuntu22.04
FROM ghcr.io/break95/root-base:latest

COPY bench.py /opt/bench.py
COPY python-runner.py /opt/python-runner.py

COPY HeadNode.py /usr/local/lib/root/DistRDF/HeadNode.py
