# The coordinator doesn't need the root base image, we can work with much less.
#FROM ubuntu:22.04
# Now that the last reduction is performed in the coordinator we need it. :)
FROM ghcr.io/break95/root-base

COPY python-runner.py /opt/python-runner.py
#COPY HeadNode.py /usr/local/lib/root/DistRDF/HeadNode.py

